# Generated by Django 6.0.4 on 2026-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("buyers", models.IntegerField()),
                ("sellers", models.IntegerField()),
                ("prices", models.JSONField()),
                ("demand", models.JSONField()),
                ("sales", models.JSONField()),
            ],
        ),
    ]
