# Generated by Django 6.0.4 on 2026-05-05 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("competitive", "Perfect Competition"),
                            ("oligopoly", "Oligopoly"),
                            ("monopoly", "Monopoly"),
                            ("auction", "Auction Market"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Market Types",
            },
        ),
        migrations.CreateModel(
            name="SimulationScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("bull_market", "Bull Market"),
                            ("bear_market", "Bear Market"),
                            ("recession", "Recession"),
                            ("boom", "Economic Boom"),
                            ("stable", "Stable Market"),
                            ("volatile", "Volatile Market"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("parameters", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="simulationrun",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="avg_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="iterations",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="market_efficiency",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="max_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="min_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="price_elasticity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="price_volatility",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="total_demand",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="total_sales",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="market_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simulation.markettype",
            ),
        ),
        migrations.CreateModel(
            name="SimulationParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("num_buyers", models.IntegerField(default=50)),
                ("num_sellers", models.IntegerField(default=5)),
                ("iterations", models.IntegerField(default=200)),
                ("buyer_budget_min", models.IntegerField(default=50)),
                ("buyer_budget_max", models.IntegerField(default=200)),
                ("buyer_wtp_min", models.IntegerField(default=20)),
                ("buyer_wtp_max", models.IntegerField(default=150)),
                ("seller_price_min", models.IntegerField(default=30)),
                ("seller_price_max", models.IntegerField(default=100)),
                ("price_adjustment_factor", models.FloatField(default=0.05)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="simulation.markettype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Simulation Parameters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="parameters",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simulation.simulationparameters",
            ),
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="simulation.simulationscenario",
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["owner", "-created_at"], name="simulation__owner_i_f88c0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["market_type", "-created_at"],
                name="simulation__market__2d75eb_idx",
            ),
        ),
    ]
